name: run main.py

on:
  schedule:
    - cron: "00 22 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        env:
          GROUP_ID: ${{ secrets.GROUP_ID }}
          CHANNEL_TOKEN: ${{ secrets.CHANNEL_TOKEN }}
          CUSTOM_MESSAGE: ${{ secrets.CUSTOM_MESSAGE }}
        run: python main.py
